mixed-port: 7897
allow-lan: false
mode: rule
log-level: info
external-controller: 0.0.0.0:9090 
find-process-mode: strict 
tcp-concurrent: true
ipv6: false
global-client-fingerprint: chrome

geodata-mode: true
geox-url:
  geoip: "https://raw.githubusercontent.com/soffchen/geoip/release/geoip-only-cn-private.dat"
  geosite: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://raw.githubusercontent.com/soffchen/geoip/release/Country-only-cn-private.mmdb"
  
profile:
  store-selected: true
  store-fake-ip: true 

sniffer:               
  enable: true
  parse-pure-ip: true 
  sniff:
    TLS:            
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    QUIC:
      ports: [443, 8443]

dns:
  enable: true
  prefer-h3: false
  ipv6: false
  listen: 0.0.0.0:53
  default-nameserver:
      - system
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter: ['*.lan', 'cable.auth.com', '*.msftconnecttest.com', '*.msftncsi.com', 'network-test.debian.org', 'detectportal.firefox.com', 'resolver1.opendns.com', '*.srv.nintendo.net', '*.stun.playstation.net', 'xbox.*.microsoft.com', '*.xboxlive.com', 'stun.*', 'global.turn.twilio.com', 'global.stun.twilio.com', 'localhost.*.qq.com', 'localhost.*.weixin.qq.com', '*.logon.battlenet.com.cn', '*.logon.battle.net', '*.blzstatic.cn', 'music.163.com', '*.music.163.com', '*.126.net', 'musicapi.taihe.com', 'music.taihe.com', 'songsearch.kugou.com', 'trackercdn.kugou.com', '*.kuwo.cn', 'api-jooxtt.sanook.com', 'api.joox.com', 'joox.com', 'y.qq.com', '*.y.qq.com', 'streamoc.music.tc.qq.com', 'mobileoc.music.tc.qq.com', 'isure.stream.qqmusic.qq.com', 'dl.stream.qqmusic.qq.com', 'aqqmusic.tc.qq.com', 'amobile.music.tc.qq.com', '*.xiami.com', '*.music.migu.cn', 'music.migu.cn', 'proxy.golang.org', '*.mcdn.bilivideo.cn', '*.cmpassport.com', 'id6.me', 'open.e.189.cn', 'mdn.open.wo.cn', 'opencloud.wostore.cn', 'auth.wosms.cn', '*.jegotrip.com.cn', '*.icitymobile.mobi', '*.pingan.com.cn', '*.cmbchina.com', 'pool.ntp.org', '*.pool.ntp.org', 'ntp.*.com', 'time.*.com', 'ntp?.*.com', 'time?.*.com', 'time.*.gov', 'time.*.edu.cn', '*.ntp.org.cn', 'PDC._msDCS.*.*', 'DC._msDCS.*.*', 'GC._msDCS.*.*']  
  nameserver:
      - 223.5.5.5
      - 114.114.114.114
      - 119.29.29.29

proxy-providers:
    subscribe_groups:
        type: http # http 的 path 可空置,默认储存路径为 homedir的proxies文件夹,文件名为url的md5
        url: "" #订阅链接存放在双引号内
        interval: 86400 #机场订阅自动更新时间 单位：秒
        path: ./config.yaml # 默认只允许存储在 clash 的 Home Dir，如果想存储到任意位置，添加环境变量 SKIP_SAFE_PATH_CHECK=1
        health-check:
            enable: true
            interval: 83214
            # lazy: true
            url: http://connectivitycheck.gstatic.com/generate_204

proxy-groups:    
    - name: "PROXY"
      type: select # 下面开启了自动测速
      use:
          - subscribe_groups 
          
    - name: "Youtube"
      type: select # 下面开启了自动测速
      proxies:
          - "PROXY"
      use:
          - subscribe_groups  
          
    - name: "Telegram"
      type: select # 下面开启了自动测速
      proxies:
#         - test 这里填写你的自建节点
          - "PROXY"
      use:
          - subscribe_groups  
                
    - name: "Spotify"
      type: select # 下面开启了自动测速
      proxies:
#         - test 这里填写你的自建节点
          - "Auto"
      use:
          - subscribe_groups  
          
    - name: "Twitter"
      type: select # 下面开启了自动测速
      proxies:
#         - test 这里填写你的自建节点
          - "Auto"
      use:
          - subscribe_groups 
            
    - name: "GoogleFCM"
      type: select # 下面开启了自动测速
      proxies:
#         - test 这里填写你的自建节点
          - "Auto"
      use:
          - subscribe_groups  
          
    - name: "GoogleVoice"
      type: select # 下面开启了自动测速
      proxies:
#         - test 这里填写你的自建节点
          - "Auto"
      use:
          - subscribe_groups  
          
    - name: "GoogleServices"
      type: select # 下面开启了自动测速
      proxies:
#         - test 这里填写你的自建节点
          - "Auto"
      use:
          - subscribe_groups  
        
    - name: "OpenAI"
      type: select # 下面开启了自动测速
      proxies:
#         - test 这里填写你的自建节点
          - "Auto"
      use:
          - subscribe_groups           

# Tiktok      
    - name: "Tiktok"
      type: select # 下面开启了自动测速
      proxies:
#         - test 这里填写你的自建节点
          - "Auto"
      use:
          - subscribe_groups        


# Copilot
    - name: "Copilot"
      type: select # 下面开启了自动测速
      proxies:
#         - test 这里填写你的自建节点
          - "Auto"
      use:
          - subscribe_groups    
