mixed-port: 7897
allow-lan: false
mode: rule
log-level: info
external-controller: 0.0.0.0:9090 
find-process-mode: strict 
tcp-concurrent: true
ipv6: false
global-client-fingerprint: chrome

geodata-mode: true
geox-url:
  geoip: "https://hub.gitmirror.com/https://github.com/soffchen/sing-geoip/releases/latest/download/geoip-cn.db"
  geosite: "https://hub.gitmirror.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.db"
  mmdb: "https://hub.gitmirror.com/https://raw.githubusercontent.com/soffchen/geoip/release/Country-only-cn-private.mmdb"
  
profile:
  store-selected: true
  store-fake-ip: true 

ntp:
  enable: true
  write-to-system: false
  server: time.apple.com
  port: 123
  interval: 30

sniffer:               
  enable: true
  parse-pure-ip: true 
  sniff:
    TLS:            
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true

dns:
  enable: true
  prefer-h3: false
  ipv6: false
  listen: 0.0.0.0:53
  default-nameserver:
      - system
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16  
  nameserver:
      - 223.5.5.5
      - 114.114.114.114
      - 119.29.29.29
      
proxy-providers:
    subscribe_groups:
        type: http
        url: "https://z.luxury/link/MDQfVA0MPCmhKI2c?sub=4"
        interval: 86400 
        path: ./providers.yaml
        health-check:
            enable: true
            interval: 83214
            url: http://connectivitycheck.gstatic.com/generate_204

proxy-groups:    
    - name: "Proxy"
      type: select
      use:
          - subscribe_groups 
          
    - name: "YouTube"
      type: select
      proxies:
          - "Proxy"
      use:
          - subscribe_groups  
          
    - name: "Telegram"
      type: select
      proxies:
          - "Proxy"
      use:
          - subscribe_groups  
                
    - name: "Spotify"
      type: select
      proxies:
          - "Proxy"
      use:
          - subscribe_groups  
          
    - name: "Twitter"
      type: select
      proxies:
          - "Proxy"
      use:
          - subscribe_groups 
            
    - name: "GoogleFCM"
      type: select
      proxies:
          - "Proxy"
      use:
          - subscribe_groups  
          
    - name: "GoogleVoice"
      type: select
      proxies:
          - "Proxy"
      use:
          - subscribe_groups  
          
    - name: "GoogleServices"
      type: select
      proxies:
          - "Proxy"
      use:
          - subscribe_groups  
        
    - name: "OpenAI"
      type: select
      proxies:
          - "Proxy"
      use:
          - subscribe_groups           
    
    - name: "TikTok"
      type: select
      proxies:
          - "Proxy"
      use:
          - subscribe_groups        
             
    - name: "FINAL"
      type: select
      proxies:
          - "Proxy"
          - "DIRECT"    
            

rule-providers:     
    Reject_Custom:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://hub.gitmirror.com/https://raw.githubusercontent.com/asdfcreate/Custom_Rule/master/Reject_Custom.list"  
  
    Reject_MIUI_Custom:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://hub.gitmirror.com/https://raw.githubusercontent.com/asdfcreate/Custom_Rule/master/Reject_MIUI_Custom.list"  
        
    sogouinput:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://ruleset.skk.moe/Clash/non_ip/sogouinput.txt"  
        
    BlockHttpDNS:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://hub.gitmirror.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BlockHttpDNS/BlockHttpDNS.list"  
        
    Advertising:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://hub.gitmirror.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising.list"  
        
    YouTube:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://hub.gitmirror.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list"  
        
    Telegram:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://hub.gitmirror.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list"  
        
    Telegram_Custom:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://hub.gitmirror.com/https://raw.githubusercontent.com/asdfcreate/Custom_Rule/master/Telegram_Custom.list"  

    Spotify:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://hub.gitmirror.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list"  
        
    Twitter:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://hub.gitmirror.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.list"  
        
    GoogleFCM:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://hub.gitmirror.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.list"  
        
    GoogleVoice:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://hub.gitmirror.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleVoice/GoogleVoice.list"  
        
    GoogleServices:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://hub.gitmirror.com/https://raw.githubusercontent.com/asdfcreate/Custom_Rule/master/Google_Services.list"  
        
    OpenAI:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://hub.gitmirror.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list"  
        
    ChatGPT_Voice:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://hub.gitmirror.com/https://raw.githubusercontent.com/Repcz/Tool/X/Clash/Rules/ChatGPT_Voice.list"  

    OpenAI_Custom:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://hub.gitmirror.com/https://raw.githubusercontent.com/asdfcreate/Custom_Rule/master/OpenAI_Custom.list" 

    TikTok:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://hub.gitmirror.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list"  
        
    LocalAreaNetwork:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://hub.gitmirror.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list"  
        
    Direct_Custom:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://hub.gitmirror.com/https://raw.githubusercontent.com/asdfcreate/Custom_Rule/master/Direct_Custom.list" 

    Lan:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://hub.gitmirror.com/https://raw.githubusercontent.com/Repcz/Tool/X/Clash/Rules/Lan.list" 

    Proxy_Custom:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://hub.gitmirror.com/https://raw.githubusercontent.com/asdfcreate/Custom_Rule/master/Proxy_Custom.list"  

rules:
    - AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((GEOSITE,cn))),REJECT
    - AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((GEOIP,CN))),REJECT
    - RULE-SET,Reject_Custom,REJECT    
    - RULE-SET,Reject_MIUI_Custom,REJECT
    - RULE-SET,sogouinput,REJECT
    - RULE-SET,BlockHttpDNS,REJECT
    - RULE-SET,Advertising,REJECT  
    - RULE-SET,YouTube,YouTube
    - RULE-SET,Telegram,Telegram      
    - RULE-SET,Telegram_Custom,Telegram   
    - RULE-SET,Spotify,Spotify   
    - RULE-SET,Twitter,Twitter 
    - RULE-SET,GoogleFCM,GoogleFCM
    - RULE-SET,GoogleVoice,GoogleVoice
    - RULE-SET,GoogleServices,GoogleServices
    - RULE-SET,OpenAI,OpenAI
    - RULE-SET,ChatGPT_Voice,OpenAI
    - RULE-SET,OpenAI_Custom,OpenAI
    - RULE-SET,TikTok,TikTok
    - RULE-SET,Twitter,Twitter
    - RULE-SET,LocalAreaNetwork,DIRECT
    - RULE-SET,Lan,DIRECT
    - RULE-SET,Direct_Custom,DIRECT
    - GEOSITE,cn,DIRECT
    - GEOSITE,tld-cn,DIRECT
    - GEOSITE,private,DIRECT
    - GEOIP,CN,DIRECT,no-resolve
    - RULE-SET,Proxy_Custom,Proxy
    - GEOSITE,gfw,Proxy
    - GEOSITE,geolocation-!cn,Proxy
    - MATCH,FINAL
