mixed-port: 7897
allow-lan: false
mode: rule
log-level: info
external-controller: 0.0.0.0:9090 
find-process-mode: strict 
tcp-concurrent: true
ipv6: false
global-client-fingerprint: chrome

geodata-mode: true
geox-url:
  geoip: "https://raw.githubusercontent.com/soffchen/geoip/release/geoip-only-cn-private.dat"
  geosite: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://raw.githubusercontent.com/soffchen/geoip/release/Country-only-cn-private.mmdb"
  
profile:
  store-selected: true
  store-fake-ip: true 

sniffer:               
  enable: true
  parse-pure-ip: true 
  sniff:
    TLS:            
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    QUIC:
      ports: [443, 8443]

dns:
  enable: true
  prefer-h3: false
  ipv6: false
  listen: 0.0.0.0:53
  default-nameserver:
      - system
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter: ['*.lan', 'cable.auth.com', '*.msftconnecttest.com', '*.msftncsi.com', 'network-test.debian.org', 'detectportal.firefox.com', 'resolver1.opendns.com', '*.srv.nintendo.net', '*.stun.playstation.net', 'xbox.*.microsoft.com', '*.xboxlive.com', 'stun.*', 'global.turn.twilio.com', 'global.stun.twilio.com', 'localhost.*.qq.com', 'localhost.*.weixin.qq.com', '*.logon.battlenet.com.cn', '*.logon.battle.net', '*.blzstatic.cn', 'music.163.com', '*.music.163.com', '*.126.net', 'musicapi.taihe.com', 'music.taihe.com', 'songsearch.kugou.com', 'trackercdn.kugou.com', '*.kuwo.cn', 'api-jooxtt.sanook.com', 'api.joox.com', 'joox.com', 'y.qq.com', '*.y.qq.com', 'streamoc.music.tc.qq.com', 'mobileoc.music.tc.qq.com', 'isure.stream.qqmusic.qq.com', 'dl.stream.qqmusic.qq.com', 'aqqmusic.tc.qq.com', 'amobile.music.tc.qq.com', '*.xiami.com', '*.music.migu.cn', 'music.migu.cn', 'proxy.golang.org', '*.mcdn.bilivideo.cn', '*.cmpassport.com', 'id6.me', 'open.e.189.cn', 'mdn.open.wo.cn', 'opencloud.wostore.cn', 'auth.wosms.cn', '*.jegotrip.com.cn', '*.icitymobile.mobi', '*.pingan.com.cn', '*.cmbchina.com', 'pool.ntp.org', '*.pool.ntp.org', 'ntp.*.com', 'time.*.com', 'ntp?.*.com', 'time?.*.com', 'time.*.gov', 'time.*.edu.cn', '*.ntp.org.cn', 'PDC._msDCS.*.*', 'DC._msDCS.*.*', 'GC._msDCS.*.*']  
  nameserver:
      - 223.5.5.5
      - 114.114.114.114
      - 119.29.29.29

proxy-providers:
    subscribe_groups:
        type: http 
        url: ""
        interval: 86400 
        path: ./config.yaml
        health-check:
            enable: true
            interval: 83214
            url: http://connectivitycheck.gstatic.com/generate_204

proxy-groups:    
    - name: "Proxy"
      use:
          - subscribe_groups 
          
    - name: "Youtube"
      type: select
      proxies:
          - "Proxy"
      use:
          - subscribe_groups  
          
    - name: "Telegram"
      type: select
      proxies:
          - "Proxy"
      use:
          - subscribe_groups  
                
    - name: "Spotify"
      type: select
      proxies:
          - "Proxy"
      use:
          - subscribe_groups  
          
    - name: "Twitter"
      type: select
      proxies:
          - "Proxy"
      use:
          - subscribe_groups 
            
    - name: "GoogleFCM"
      type: select
      proxies:
          - "Proxy"
      use:
          - subscribe_groups  
          
    - name: "GoogleVoice"
      type: select
      proxies:
          - "Proxy"
      use:
          - subscribe_groups  
          
    - name: "GoogleServices"
      type: select
      proxies:
          - "Proxy"
      use:
          - subscribe_groups  
        
    - name: "OpenAI"
      type: select
      proxies:
          - "Proxy"
      use:
          - subscribe_groups           
    
    - name: "Tiktok"
      type: select
      proxies:
          - "Proxy"
      use:
          - subscribe_groups        
          
    - name: "Direct"
      type: select
      proxies:
          - "DIRECT"
          
    - name: "Reject"
      type: select
      proxies:
          - "REJECT"
          
    - name: "Final"
      type: select
      proxies:
          - "Proxy"
          - "Direct"                

rule-providers:     
    Reject_Custom:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://raw.githubusercontent.com/asdfcreate/Custom_Rule/master/Reject_Custom.list"  
  
    Reject_MIUI_Custom:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://raw.githubusercontent.com/asdfcreate/Custom_Rule/master/Reject_MIUI_Custom.list"  
        
    sogouinput:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://ruleset.skk.moe/Clash/non_ip/sogouinput.txt"  
        
    BlockHttpDNS:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BlockHttpDNS/BlockHttpDNS.list"  
        
    Advertising:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising.list"  
        
    YouTube:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list"  
        
    Telegram:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list"  
        
    Telegram_Custom:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://raw.githubusercontent.com/asdfcreate/Custom_Rule/master/Telegram_Custom.list"  

    Spotify:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list"  
        
    Twitter:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.list"  
        
    GoogleFCM:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.list"  
        
    GoogleVoice:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleVoice/GoogleVoice.list"  
        
    GoogleServices:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://raw.githubusercontent.com/asdfcreate/Custom_Rule/master/Google_Services.list"  
        
    OpenAI:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list"  
        
    ChatGPT_Voice:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://gitlab.com/lodepuly/vpn_tool/raw/master/Tool/Loon/Rule/ChatGPT_Voice.list"  

    OpenAI_Custom:
        type: http
        behavior: classical    
        format: text
        interval: 86400
        url: "https://raw.githubusercontent.com/asdfcreate/Custom_Rule/master/OpenAI_Custom.list"  







