mixed-port: 7897
allow-lan: false
mode: rule
log-level: info
external-controller: 0.0.0.0:9090 
find-process-mode: strict 
tcp-concurrent: true
ipv6: false
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true 

sniffer:               
  enable: true
  parse-pure-ip: true 
  sniff:
    TLS:            
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
      
geodata-mode: true
geodata-loader: memconservative
geo-auto-update: true
geo-update-interval: 8
geox-url:
  geoip: "https://raw.githubusercontent.com/soffchen/geoip/release/geoip-only-cn-private.dat"
  geosite: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://raw.githubusercontent.com/soffchen/geoip/release/Country-only-cn-private.mmdb" 
  
dns:
  enable: true
  prefer-h3: false
  ipv6: false
  listen: :1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter: [ '*.lan', 'cable.auth.com', '*.msftconnecttest.com', '*.msftncsi.com', 'network-test.debian.org', 'detectportal.firefox.com', 'resolver1.opendns.com', '*.srv.nintendo.net', '*.stun.playstation.net', 'xbox.*.microsoft.com', '*.xboxlive.com', 'stun.*', 'global.turn.twilio.com', 'global.stun.twilio.com', 'localhost.*.qq.com', 'localhost.*.weixin.qq.com', '*.logon.battlenet.com.cn', '*.logon.battle.net', '*.blzstatic.cn', 'music.163.com', '*.music.163.com', '*.126.net', 'musicapi.taihe.com', 'music.taihe.com', 'songsearch.kugou.com', 'trackercdn.kugou.com', '*.kuwo.cn', 'api-jooxtt.sanook.com', 'api.joox.com', 'joox.com', 'y.qq.com', '*.y.qq.com', 'streamoc.music.tc.qq.com', 'mobileoc.music.tc.qq.com', 'isure.stream.qqmusic.qq.com', 'dl.stream.qqmusic.qq.com', 'aqqmusic.tc.qq.com', 'amobile.music.tc.qq.com', '*.xiami.com', '*.music.migu.cn', 'music.migu.cn', 'proxy.golang.org', '*.mcdn.bilivideo.cn', '*.cmpassport.com', 'id6.me', 'open.e.189.cn', 'mdn.open.wo.cn', 'opencloud.wostore.cn', 'auth.wosms.cn', '*.jegotrip.com.cn', '*.icitymobile.mobi', '*.pingan.com.cn', '*.cmbchina.com', 'pool.ntp.org', '*.pool.ntp.org', 'ntp.*.com', 'time.*.com', 'ntp?.*.com', 'time?.*.com', 'time.*.gov', 'time.*.edu.cn', '*.ntp.org.cn', 'PDC._msDCS.*.*', 'DC._msDCS.*.*', 'GC._msDCS.*.*' ] 
  nameserver-policy: { '*.google.com': 8.8.8.8, '*.tw': 1.1.1.1, testflight.apple.com: 8.8.8.8, '*.tmall.com': 223.5.5.5, '*.taobao.com': 223.5.5.5, '*.alicdn.com': 223.5.5.5, '*.aliyun.com': 223.5.5.5, '*.alipay*.com': 223.5.5.5, '*.alibaba*.com': 223.5.5.5, '*.alimama*.com': 223.5.5.5, '*.qq.com': 114.114.114.114, '*.tencent.com': 114.114.114.114, '*.weixin.com': 114.114.114.114, '*.qpic.cn': 114.114.114.114, '*.jd.com': 114.114.114.114, '*.bilibili.com': 114.114.114.114, hdslb.com: 114.114.114.114, '*.163.com': 119.29.29.29, '*.126.com': 119.29.29.29, '*.126.net': 114.114.114.114, '*.127.net': 114.114.114.114, '*.netease.com': 114.114.114.114, '*.10010.com': 114.114.114.114, '*.unicompayment.com': 114.114.114.114, '*.ximalaya.com': 114.114.114.114, '*.baidu.com': 114.114.114.114, '*.bdstatic.com': 114.114.114.114, 'geosite:geolocation-!cn,gfw': 8.8.8.8 }
  nameserver:
      - 223.5.5.5
      - 114.114.114.114
      - 119.29.29.29
  proxy-server-nameserver:
    - 8.8.8.8
