mixed-port: 7897
allow-lan: false
mode: Rule
log-level: info
external-controller: :9090


geodata-mode: true
geox-url:
  geoip: "https://raw.githubusercontent.com/soffchen/geoip/release/geoip-only-cn-private.dat"
  geosite: "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat"
