mixed-port: 7897
allow-lan: false
mode: rule
log-level: info
external-controller: 0.0.0.0:9090 
find-process-mode: strict 
tcp-concurrent: true
ipv6: false
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true 

ntp:
  enable: true
  write-to-system: false
  server: time.apple.com
  port: 123
  interval: 30

sniffer:               
  enable: true
  parse-pure-ip: true 
  sniff:
    TLS:            
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
      
geodata-mode: true


dns:
  enable: true
  prefer-h3: false
  ipv6: false
  listen: :1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
      - 223.5.5.5
      - 114.114.114.114
      - 119.29.29.29
