port: 7897
socks-port: 7898
allow-lan: false
mode: Rule
log-level: info
external-controller: :9090



geodata-mode: true
geox-url: 
    geoip: "https://cdn.jsdelivr.net/gh/soffchen/geoip@release/cn.dat"
    geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
