mixed-port: 7897
allow-lan: false
mode: rule
ipv6: false
log-level: info
external-controller: :9090


dns:
  enable: true
  prefer-h3: false
  ipv6: false
  listen: :1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
      - 223.5.5.5
      - 114.114.114.114
      - 119.29.29.29
