mixed-port: 7897
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9097
find-process-mode: strict
tcp-concurrent: true
ipv6: false
global-client-fingerprint: chrome
secret: ""
external-ui: .\ui
profile:
  store-selected: true
  store-fake-ip: true
sniffer:
  enable: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - Mijia Cloud
ntp:
  enable: true
  write-to-system: false
  server: time1.aliyun.com
  port: 123
  interval: 30
geodata-mode: true
geodata-loader: memconservative
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: https://raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip-only-cn-private.dat
  geosite: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite-lite.dat
  mmdb: https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country-only-cn-private.mmdb
dns:
  enable: true
  use-hosts: true
  cache-algorithm: arc
  prefer-h3: false
  ipv6: false
  listen: 0.0.0.0:1053
  default-nameserver:
    - tls://1.12.12.12:853
    - tls://223.5.5.5:853
    - system 
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.example"
    - "*.home.arpa"
    - "*.invalid"
    - +.lan
    - +.local
    - "*.localdomain"
    - "*.localhost"
    - +.microsoft.com
    - +.msftconnecttest.com
    - +.msftncsi.com
    - ntp.*.com
    - time-ios.apple.com
    - time-macos.apple.com
    - time.*.com
    - time.*.gov
    - +.pool.ntp.org
    - "*.cloud.tencent.com"
    - "*.pool.ntp.org"
    - pool.ntp.org
    - "*.mcdn.bilivideo.cn"
  nameserver-policy:
    rule-set:private: system
    rule-set:Reject_Custom,category-httpdns,AWAvenue-Ads-Rule-Clash: rcode://success
  nameserver:
    - tls://1.12.12.12:853
    - tls://223.5.5.5:853
    - https://223.5.5.5/dns-query
    - https://1.12.12.12/dns-query
  proxy-server-nameserver:
    - https://1.0.0.1/dns-query
    - tls://8.8.4.4:853
  fallback:
    - https://1.0.0.1/dns-query
    - tls://8.8.4.4:853
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
proxy-providers:
  provider1:
    type: http
    url: "http://test.com"
    path: ./proxy_providers/provider1.yaml
    interval: 3600
    health-check:
      enable: true
      url: http://www.bing.com
      interval: 300
      timeout: 5000
      expected-status: 204
    exclude-filter: (^3[1-8])

proxy-groups:
  - name: Proxy
    type: select
    use:
      - provider1
    
  - name: Youtube
    type: select
    proxies:
      - Proxy
    use:
      - provider1

  - name: Telegram
    type: select
    proxies:
      - Proxy
    use:
      - provider1

  - name: OpenAI
    type: select
    proxies:
      - Proxy
    use:
      - provider1

  - name: Scholar
    type: select
    proxies:
      - Proxy
      - DIRECT
    use:
      - provider1
    
  - name: Google
    type: select
    proxies:
      - Proxy
    use:
      - provider1
      
  - name: Notion
    type: select
    proxies:
      - Proxy
      - Google
    use:
      - provider1
      
  - name: ImTr
    type: select
    proxies:
      - Proxy
      - Google
    use:
      - provider1
      
  - name: Apple
    type: select
    proxies:
      - Proxy
      - DIRECT
    use:
      - provider1
      
  - name: Microsoft
    type: select
    proxies:
      - Proxy
      - DIRECT
    use:
      - provider1
      
  - name: Profile_Update
    type: select
    proxies:
      - Proxy
      - DIRECT
    use:
      - provider1
      
rule-providers:
  Reject_Custom:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/asdfcreate/Custom_Rule/master/ruleset/Reject_Custom.yaml
    path: ./providers/rule-provider_Reject_Custom.yaml
    interval: 86400
  category-httpdns:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-httpdns.yaml
    path: ./providers/rule-provider_category-httpdns.yaml
    interval: 86400
  AWAvenue-Ads-Rule-Clash:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Clash.yaml
    path: ./providers/rule-provider_AWAvenue-Ads-Rule-Clash.yaml
    interval: 86400
  youtube:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.yaml
    path: ./providers/rule-provider_youtube.yaml
    interval: 86400
  Telegram_domain:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.yaml
    path: ./providers/rule-provider_Telegram_domain.yaml
    interval: 86400
  Telegram_ipcidr:
    type: http
    behavior: ipcidr
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.yaml
    path: ./providers/rule-provider_Telegram_ipcidr.yaml
    interval: 86400
  OpenAI_domain:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/asdfcreate/Custom_Rule/master/ruleset/OpenAI_domain.yaml
    path: ./providers/rule-provider_OpenAI_domain.yaml
    interval: 86400
  OpenAI_ipcidr:
    type: http
    behavior: ipcidr
    url: https://raw.githubusercontent.com/asdfcreate/Custom_Rule/master/ruleset/OpenAI_ipcidr.yaml
    path: ./providers/rule-provider_OpenAI_ipcidr.yaml
    interval: 86400
  category-scholar-!cn:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-scholar-!cn.yaml
    path: ./providers/rule-provider_category-scholar-!cn.yaml
    interval: 86400
  Notion:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/asdfcreate/Custom_Rule/master/ruleset/Notion.yaml
    path: ./providers/rule-provider_Notion_domain.yaml
    interval: 86400
  Immersive_Translate:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/asdfcreate/Custom_Rule/master/ruleset/Immersive_Translate.yaml
    path: ./providers/rule-provider_Immersive_Translate.yaml
    interval: 86400
  google:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.yaml
    path: ./providers/rule-provider_google.yaml
    interval: 86400
  Apple_Domain:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple_Domain.yaml
    path: ./providers/rule-provider_Apple_Domain.yaml
    interval: 86400
  microsoft:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.yaml
    path: ./providers/rule-provider_microsoft.yaml
    interval: 86400
  Proxy_Custom:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/asdfcreate/Custom_Rule/master/ruleset/Proxy_Custom.yaml
    path: ./providers/rule-provider_Proxy_Custom.yaml
    interval: 86400
  Global_Domain:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global_Domain.yaml
    path: ./providers/rule-provider_Global_Domain.yaml
    interval: 86400
  geolocation-!cn:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.yaml
    path: ./providers/rule-provider_geolocation-!cn.yaml
    interval: 86400
  private:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt
    path: ./providers/rule-provider_private.yaml
    interval: 86400
  Direct_Custom:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/asdfcreate/Custom_Rule/master/ruleset/Direct_Custom.yaml
    path: ./providers/rule-provider_Direct_Custom.yaml
    interval: 86400
  ChinaMax_Domain:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_Domain.yaml
    path: ./providers/rule-provider_ChinaMax_Domain.yaml
    interval: 86400
  ChinaIPsBGP:
    type: http
    behavior: ipcidr
    url: https://raw.githubusercontent.com/soffchen/GeoIP2-CN/release/clash-rule-provider.yml
    path: ./providers/rule-provider_ChinaIPsBGP.yaml
    interval: 3600
rules:
  - AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((RULE-SET,ChinaMax_Domain))),REJECT
  - AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((RULE-SET,ChinaIPsBGP,no-resolve))),REJECT
  - RULE-SET,Reject_Custom,REJECT
  - RULE-SET,category-httpdns,REJECT
  - RULE-SET,AWAvenue-Ads-Rule-Clash,REJECT
  - RULE-SET,youtube,Youtube
  - DOMAIN-KEYWORD,telegram,Telegram
  - DOMAIN-KEYWORD,nicegram,Telegram
  - RULE-SET,Telegram_domain,Telegram
  - RULE-SET,Telegram_ipcidr,Telegram,no-resolve
  - RULE-SET,OpenAI_domain,OpenAI
  - RULE-SET,OpenAI_ipcidr,OpenAI,no-resolve
  - DOMAIN-KEYWORD,openaicom-api,OpenAI
  - RULE-SET,category-scholar-!cn,Scholar
  - AND,((PROCESS-NAME,Clash Verge.exe),(DOMAIN-SUFFIX,workers.dev)),Profile_Update
  - AND,((PROCESS-NAME,mihomo),(DOMAIN-SUFFIX,workers.dev)),Profile_Update
  - AND,((PROCESS-NAME,mihomo),(DOMAIN-SUFFIX,githubusercontent.com)),Profile_Update
  - AND,((PROCESS-NAME,mihomo),(DOMAIN-SUFFIX,gitlab.com)),Profile_Update
  - AND,((PROCESS-NAME,mihomo),(DOMAIN-SUFFIX,id9.cc)),Profile_Update
  - RULE-SET,Notion,Notion
  - RULE-SET,Immersive_Translate,ImTr
  - RULE-SET,google,Google
  - RULE-SET,Apple_Domain,Apple
  - RULE-SET,microsoft,Microsoft
  - RULE-SET,Proxy_Custom,Proxy
  - RULE-SET,Global_Domain,Proxy
  - RULE-SET,geolocation-!cn,Proxy
  - RULE-SET,private,DIRECT
  - RULE-SET,Direct_Custom,DIRECT
  - RULE-SET,ChinaMax_Domain,DIRECT
  - RULE-SET,ChinaIPsBGP,DIRECT,no-resolve
  - GEOIP,PRIVATE,DIRECT,no-resolve
  - GEOIP,CN,DIRECT,no-resolve
  - MATCH,Proxy
