mixed-port: 7897
allow-lan: false
mode: rule
log-level: info
external-controller: 0.0.0.0:9090 
find-process-mode: strict 
tcp-concurrent: true
ipv6: false
global-client-fingerprint: chrome
keep-alive-interval: 30

profile:
  store-selected: true
  store-fake-ip: true 

sniffer:               
  enable: true
  parse-pure-ip: true 
  sniff:
    TLS:            
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
      
geodata-mode: true
geodata-loader: memconservative
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip-only-cn-private.dat"
  geosite: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite-lite.dat"
  mmdb: "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country-only-cn-private.mmdb" 
  
dns:
  enable: true
  prefer-h3: false
  ipv6: false
  listen: :1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter: [ '*.lan', 'cable.auth.com', '*.msftconnecttest.com', '*.msftncsi.com', 'xbox.*.microsoft.com', '*.xboxlive.com', 'stun.*', 'localhost.*.qq.com', 'localhost.*.weixin.qq.com', 'localhost.ptlogin2.qq.com', '*.mcdn.bilivideo.cn', '*.cmpassport.com', '*.cmbchina.com', 'pool.ntp.org', '*.pool.ntp.org', 'ntp.*.com', 'time.*.com', 'ntp?.*.com', 'time?.*.com', 'time.*.gov', 'time.*.edu.cn', '*.ntp.org.cn', 'PDC._msDCS.*.*', 'DC._msDCS.*.*', 'GC._msDCS.*.*' ] 
  nameserver-policy: { 'rule-set:private': system }
  nameserver:
    - 223.5.5.5
    - 114.114.114.114
    - 119.29.29.29
  proxy-server-nameserver:
      - https://1.0.0.1/dns-query
      - tls://8.8.4.4:853
  fallback:
    - https://1.0.0.1/dns-query
    - tls://8.8.4.4:853
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
