mixed-port: 7897
socks-port: 7898
port: 7899
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9097
find-process-mode: off
tcp-concurrent: true
ipv6: false
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true 

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - Mijia Cloud
      
ntp:
  enable: true
  write-to-system: false
  server: time1.aliyun.com
  port: 123
  interval: 30
  
geodata-mode: true
geosite-matcher: succinct
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: "https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash/geoip-lite.dat"
  geosite: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite-lite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/DustinWin/ruleset_geodata@clash/Country-lite.mmdb" 
  asn: "https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash/Country-ASN.mmdb"
  
dns:
  enable: true
  use-hosts: false
  use-system-hosts: false
  respect-rules: true
  cache-algorithm: arc
  prefer-h3: false
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.example"
    - "*.home.arpa"
    - "*.invalid"
    - "+.lan"
    - "+.local"
    - "*.localdomain"
    - "*.localhost"
    #  Windows 10 Connnect Detection
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
  nameserver-policy: 
    "rule-set:private": "system" 
    "auth.ysu.edu.cn": "system" 
  nameserver:
    - https://223.5.5.5/dns-query#h3=true
    - https://1.12.12.12/dns-query
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query
    - https://1.12.12.12/dns-query
  fallback:
    - https://1.1.1.1/dns-query#h3=true
    - https://8.8.8.8/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
